name: levinenv
channels:
  - conda-forge
dependencies:
  - python=3.8
  - psychopy
  - numpy
  - scipy
  - matplotlib
  - pandas
  - jupyter
  - plotnine
  - click
  - black
  - pip
  - pytest
  - rope
  - h5py
  - seaborn
  - pip:
      - psychtoolbox
      - pygame
      - pyo
      - pyfirmata
      - pyparallel; platform_system != "Windows"
      - SoundFile; platform_system == "Windows"
      - websocket_client
      - control
      - plux
